# antora-playbook.yml
site:
  robots: allow
  start_page: sample-docs::index.adoc
  title: Writing Samples
  url: https://danroscigno.github.io/antora-docs-site/
content:
  sources:
  - url: ./
    branches: HEAD
    start_paths:
    - content/*
runtime:
  cache_dir: ./build/cache
ui:
  bundle:
    url: ./build/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
urls:
  html_extension_style: indexify
antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension' # <1>
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts # <3>
      mermaid_initialize_options: # <4>
        start_on_load: true

