# antora-playbook.yml
site:
  robots: allow
  start_page: sample-docs::index.adoc
  title: Writing Samples
  url: https://danroscigno.github.io/antora-docs-site/
content:
  sources:
  - url: ./
    branches: HEAD
    start_paths:
    - content/*
runtime:
  cache_dir: ./build/cache
ui:
  bundle:
    url: ./build/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
urls:
  html_extension_style: indexify
